name: List Action
description: Request to add an action to PyAction marketplace
title: "Add ___ to the marketplace"
labels: ["marketplace"]
assignees: lnxpy
body:
  - type: input
    attributes:
      label: Title
      description: Action title
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe the action and tell what it does.
      render: markdown
    validations:
      required: true

  - type: input
    attributes:
      label: Repository
      description: Repository address
      placeholder: https://github.com/...
    validations:
      required: true
