name: Testing Action
description: Example testing PyAction action
author: Sadra Yahyapour

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  github_token:
    description: The GitHub auth token
    default: ${{ github.token }}
    required: true

  repository:
    description: The repository name in the form of "<owner>/<repo>"
    default: ${{ github.repository }}
    required: true

  test_name:
    description: Testing name
    required: true

  test_age:
    description: Testing age
    required: true

outputs:
  message:
    description: Testing message
