name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    name: Running Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Run tox
        run: uvx --with tox-uv tox -e py

  quality-checking:
    name: Running Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Run tox
        run: uvx --with tox-uv tox -e check

  type-checking:
    name: Running Type Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Run tox
        run: uvx --with tox-uv tox -e type-check
